### ISSUE TITLE
Export to FC: Verify New Workspace is New

### ISSUE THREAD

**Issue by coverbeck** [DataBiosphere/boardwalk#9]
In the Export to FireCloud dialog, the user can either select an existing workspace or specify the name of a new workspace.

We should validate client-side that the new workspace the user types in is actually new, i.e., they don't accidentally type in the name of an existing workspace.

**Comment by cricketsloan** [comment]
This issue is closing to consolidate Boardwalk tickets, it is now being tracked in https://github.com/BD2KGenomics/boardwalk/issues/10
